travis:
  secure:
    BINSTAR_TOKEN: O4RyiFP6Fvqp7YlXLDHePDEo+a8D5DY9jzI94kO0xrpsVgao28L0HaF4q+5qxrwb7yqu1+hLDzsYuKYIO5NvN9FofMqEX+FdF+3PF4LW3sYZ8wQr9eQ/eZ37wgPaRRJfNm0X0RQ5DEDRhqs+yw29bB+G61KUVqq60dxoCI3Sa3iD/fA1dpztgeVJFEOyxh8Dr0QaAHqqwgzxTVSHIrOWqmFitOH8RIkceeGYW9NnjDgR0f4bYBraoq0H1Xf5TSoJSOY0JNHmFirqXPP+DlhrsbPLQS1+i3b+w1QZyG6fxV3QD/I7L5KomAsabtbBAUahske2NhS1fiF8QPTrmTrwQ2SPpSt2HLguS/9BONuwxADl8RkamLDUWOvODrXnZqh8Ttjc5sPpfEApectvA2HX1RX6KT34L1T9KAuweuDfCsHMv92MNDJZU/lY0xZA2xWEWU0LVHiAZo1DHD/ovwOAPEMmW6LTLlDKioGfPx3wSmEoxIvD4yoiXJ5v+9U7+2CJIEgx+j/RASQKvws1LF7crR1gaiwFXgfU7ELz0x3ebLp0Du58BjMxHPzplD8hjGXWFyJlUBHNAICvAr3iLqRpDKVXe1OzknAynI4mnoggwRId5VyG95t29W7kMTY3DiF9/8quEp6gX9rGKwDRfsfF6fMed4xJ+TiNIUOoke6qvp8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
